# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dceb551a18f8376f4a0321d3d137507821de82720b2a43f42bf045f2e4a895f85b211b3d369dca4b8fd3dd999b7ac889dc1f589a65c75b82d021548fc6ec3999

test:
  secret_key_base: c40e1a54933403615dc7f926c4249118065083499d271e5d360a3d63caf499140bfc8fbba04b640416610033d6aa8d55dbf0939a1a18e5bf9c24287e30dac42a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
